/* Generated by Together */

package com.paymentech.eis.tools.xml;

/** This exception is thrown when condition occurred */
public class AttributeNotFound extends Exception {
    /** Constructs an Exception without a message. */
    public AttributeNotFound() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public AttributeNotFound(String message) {
        super(message);
    }
}
