/* Generated by Together */

package com.paymentech.eis.tools.xml;

/**
 * This exception is thrown when condition occurred
 */
public class TagNotFound extends Exception {
  /**
   * Constructs an Exception without a message.
   */
  public TagNotFound() {
    super();
  }

  /**
   * Constructs an Exception with a detailed message.
   *
   * @param Message The message associated with the exception.
   */
  public TagNotFound(String message) {
    super(message);
  }
}
